### ISSUE TITLE
Bug in avr.py: replace "b" with ord(b)

### ISSUE THREAD

**Issue by scalese** [junzis/sil#3]
Hello,

I could not make the original code work in avr mode; the buffer string would not write more than one character.  I solved this by editing avr.py starting on line 23; replacing "b" with "ord(b)" and in line 32, replacing "chr(b)" with "b".  This allows the if statements to work and the message to complete.

I'm a novice programmer, so this may not be the most elegant solution.

**Comment by junzis** [comment]
May I ask which version of the Python are you using? Is it 2 or 3?

**Comment by scalese** [comment]
I have been using Python 2.

**Comment by junzis** [comment]
I see now. It may because of the python version. I have been using Python 3 for quite a while. 
Would you mind to try it under Python 3 to see if it will work?

**Comment by scalese** [comment]
The code without my edit does work in python3

I did have to change the indent on line 19 of avr.py from a tab to spaces.  That could be an artifact from my local modification of the file however.

**Comment by junzis** [comment]
Sounds good!
